# Generated by Django 3.2 on 2021-09-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_Id', models.IntegerField()),
                ('Customer_Name', models.CharField(max_length=200, null=True)),
                ('Open_Date', models.DateTimeField(auto_now_add=True, null=True)),
                ('Last_Consulted_Date', models.DateTimeField(auto_now_add=True, null=True)),
                ('Vaccination_Id', models.CharField(max_length=200, null=True)),
                ('Dr_Name', models.CharField(max_length=200, null=True)),
                ('State', models.CharField(max_length=200, null=True)),
                ('DOB', models.CharField(max_length=200, null=True)),
                ('Is_Active', models.BooleanField(default=False)),
            ],
        ),
    ]
