# Generated by Django 3.2 on 2021-09-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Country',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
