# Generated by Django 3.2 on 2021-09-04 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210904_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country_Name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerByCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_Id', models.IntegerField()),
                ('Customer_Name', models.CharField(max_length=200, null=True)),
                ('Open_Date', models.CharField(max_length=200, null=True)),
                ('Last_Consulted_Date', models.CharField(max_length=200, null=True)),
                ('Vaccination_Id', models.CharField(max_length=200, null=True)),
                ('Dr_Name', models.CharField(max_length=200, null=True)),
                ('State', models.CharField(max_length=200, null=True)),
                ('DOB', models.CharField(max_length=200, null=True)),
                ('Is_Active', models.BooleanField(default=False)),
                ('Country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.country')),
            ],
        ),
    ]
